logFilters:
  - code: YN0002
    level: discard
  - code: YN0007
    level: discard
  - code: YN0013
    level: discard
  - code: YN0032
    level: discard
  - code: YN0060
    level: discard
  - code: YN0061
    level: discard

nmMode: hardlinks-local

nodeLinker: node-modules

npmRegistryServer: "https://npm.dev.wixpress.com"

yarnPath: .yarn/releases/yarn-4.6.0.cjs
